#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
    path: /
    controller: App\Controller\AccueilController::index
visiteur:
    path: /visiteur
    controller: App\Controller\VisiteurController::index    
consulter:
    path: /affichage/consulter/{login}/{mois}/{annee}
    controller: App\Controller\ConsulterController::index
fiche:
    path: /fiche
    controller: App\Controller\FicheController::index
saisir:
    path: /affichage/saisir
    controller: App\Controller\SaisirController::index
connexion: 
    path: /connexion
    controller: App\Controller\ConnexionController::index
affichage:
    path: /affichage
    controller: App\Controller\AffichageController::index

comptable:
    path: /comptable
    controller: App\Controller\ComptableController::index
cocomptable:
    path: /cocomptable
    controller: App\Controller\CocomptableController::index